MyLogicApp-sample/Controllers/IsAtamaController.cs
using MyLogicApp_sample.BLL.Managers;
using MyLogicApp_sample.ENTITY.Models.WorkFlow;
using MyLogicApp_sample.Web.Models;
using System.Web.Mvc;

namespace MyLogicApp_sample.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class IsAtamaController : Controller
    {
        private readonly IsAtamaManager _isAtamaManager;

        public IsAtamaController()
        {
            _isAtamaManager = new IsAtamaManager();
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult SemalariGetir()
        {
            var semalar = _isAtamaManager.SemalariGetir();

            return Json(semalar, JsonRequestBehavior.AllowGet);
        }

        public JsonResult CalisanlariGetir()
        {
            var calisanlar = _isAtamaManager.CalisanlariGetir();

            return Json(calisanlar, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AtamaKaydet(IsAtamaViewModel model)
        {
            var isAtama = new IsAtama
            {
                SemaId = model.SemaId,
                AtananKullaniciId = model.CalisanId,
                Aciklama = model.Aciklama,
                BaslangicTarihi = model.BaslangicTarihi,
                SonTarih = model.SonTarih
            };

            var result = _isAtamaManager.IsAtamaKaydet(isAtama) ? "Atama kaydedildi" : "Atama kaydedilemedi";

            return Json(result, JsonRequestBehavior.AllowGet);

        }
    }
}

MyLogicApp-sample/Controllers/IsPlaniController.cs
using MyLogicApp_sample.BLL.Managers;
using MyLogicApp_sample.ENTITY.Models;
using MyLogicApp_sample.ENTITY.Models.WorkFlow;
using MyLogicApp_sample.Web.Models;
using System.Linq;
using System.Web.Mvc;

namespace MyLogicApp_sample.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class IsPlaniController : Controller
    {
        private readonly IsPlaniManager _isPlaniManager;
        public IsPlaniController()
        {
            _isPlaniManager = new IsPlaniManager();
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult SemaKaydet(SemaViewModel model)
        {
            var sema = new Sema
            {
                Baslik = model.Baslik,
                Aciklama = model.Aciklama
            };

            var adimlar = model.Adimlar
                .Select(x => new Adim
                {
                    Baslik = x.Baslik,
                    YonlendirmeUrl = x.YonlendirmeUrl
                }).ToList();

            var result = _isPlaniManager.SemaKaydet(sema, adimlar) ? "Şema kaydedildi" : "Şema kaydedilemedi";

            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

MyLogicApp-sample/Views/Shared/_Layout.cshtml
@using MyLogicApp_sample.Controllers
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    @RenderSection("styles", required: false)

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <meta name="description" content="">
    <meta name="author" content="Frest">
    <title>@ViewBag.Title | Frest</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/app-assets/images/ico/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,600%7CIBM+Plex+Sans:300,400,500,600,700" rel="stylesheet">

    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/vendors.min.css">
    <link rel="stylesheet" type="text/css" href="../../../app-assets/vendors/css/charts/apexcharts.css">
    <link rel="stylesheet" type="text/css" href="../../../app-assets/vendors/css/extensions/swiper.min.css">
    <!-- END: Vendor CSS-->
    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/bootstrap-extended.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/colors.css">
    <link href="~/app-assets/css/components.min.css" rel="stylesheet" />
    <link href="~/app-assets/vendors/css/extensions/devexpress/dx.common.css" rel="stylesheet" />
    <link href="~/app-assets/vendors/css/extensions/devexpress/dx.softblue.css" rel="stylesheet" />
    <!-- END: Theme CSS-->
    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/core/menu/menu-types/horizontal-menu.css">
    <!-- END: Page CSS-->
    <!-- BEGIN: Custom CSS-->
    <link href="~/app-assets/css/custom.css" rel="stylesheet" />
    <!-- END: Custom CSS-->

    <script src="~/app-assets/js/core/libraries/jquery.min.js"></script>

    <!-- BEGIN: Vendor JS-->
    <script src="~/app-assets/vendors/js/vendors.min.js"></script>
    <script src="~/app-assets/fonts/LivIconsEvo/js/LivIconsEvo.tools.js"></script>
    <script src="~/app-assets/fonts/LivIconsEvo/js/LivIconsEvo.defaults.js"></script>
    <script src="~/app-assets/fonts/LivIconsEvo/js/LivIconsEvo.min.js"></script>
    <!-- BEGIN Vendor JS-->
    <!-- BEGIN: Page Vendor JS-->
    <script src="~/app-assets/vendors/js/ui/jquery.sticky.js"></script>
    <script src="../../../app-assets/vendors/js/extensions/swiper.min.js"></script>
    <!-- END: Page Vendor JS-->

    <script src="~/app-assets/vendors/js/charts/apexcharts.js"></script>
    <script src="~/app-assets/js/custom.js"></script>
</head>

<body class="horizontal-layout horizontal-menu navbar-sticky 2-columns footer-static" data-open="hover" data-menu="horizontal-menu" data-col="2-columns">
    <nav class="header-navbar navbar-expand-lg navbar navbar-with-menu navbar-fixed bg-primary navbar-brand-center">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item">
                    <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                        <h1 class="brand-text mb-0">Frest</h1>
                    </a>
                </li>
            </ul>
        </div>
        <div class="navbar-wrapper">
            <div class="navbar-container content">
                <div class="navbar-collapse" id="navbar-mobile">
                    <div class="mr-auto float-left bookmark-wrapper d-flex align-items-center">
                        <ul class="nav navbar-nav">
                            <li class="nav-item mobile-menu mr-auto">
                                <a class="nav-link nav-menu-main" href="@Url.Action("Index", "Home")">
                                    <i class="brand-text mb-0">Home</i>
                                </a>
                            </li>
                            @if (HttpContext.Current.User.IsInRole("Admin"))
                            {
                                <li class="nav-item mobile-menu mr-auto">
                                    <a class="nav-link nav-menu-main" href="@Url.Action("Index", "IsPlani")">
                                        <i class="brand-text mb-0">İş Planı Oluştur</i>
                                    </a>
                                </li>
                                <li class="nav-item mobile-menu mr-auto">
                                    <a class="nav-link nav-menu-main" href="@Url.Action("Index", "IsAtama")">
                                        <i class="brand-text">İş Atama Oluştur</i>
                                    </a>
                                </li>
                            }
                        </ul>
                    </div>
                    <ul class="nav navbar-nav float-right d-flex align-items-center">
                        @if (HttpContext.Current.User.Identity.IsAuthenticated)
                        {
                            <li class="dropdown dropdown-notification nav-item" id="btn-notify">
                                <a class="nav-link nav-link-label" href="#" data-toggle="dropdown">
                                    <i class="ficon bx bx-bell bx-tada bx-flip-horizontal"></i>
                                    <span class="badge badge-pill badge-danger badge-up" id="todo-count"> @(HomeController.GetTodoCount(HttpContext.Current.User.Identity.GetUserId()))</span>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
                                    <li class="dropdown-menu-header">
                                        <div class="dropdown-header px-1 py-75 d-flex justify-content-between">
                                            <span class="notification-title" id="todo-count">@(HomeController.GetTodoCount(HttpContext.Current.User.Identity.GetUserId())) yeni bildirim</span>
                                        </div>
                                    </li>
                                    <li class="scrollable-container media-list" id="list-tasks">
                                        
                                    </li>
                                    <li class="dropdown-menu-footer"><a class="dropdown-item p-50 text-primary justify-content-center" href="javascript:void(0)">Tüm bildirimler</a></li>
                                </ul>
                            </li>
                            <li class="nav-item mobile-menu mr-auto">
                                <a class="nav-link nav-menu-main" href="@Url.Action("Logout", "Account")">
                                    <i class="brand-text mb-0">Çıkış Yap</i>
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item mobile-menu mr-auto">
                                <a class="nav-link nav-menu-main" href="@Url.Action("Login", "Account")">
                                    <i class="brand-text mb-0">Giriş Yap</i>
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="content-wrapper">
            <div class="content-body">
                @RenderBody()
            </div>
        </div>
    </div>
    <!-- END: Content-->
    <!-- BEGIN: Footer-->
    <footer class="footer footer-static footer-light">
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        @if (HttpContext.Current.User.Identity.IsAuthenticated)
        {
            <button id="btn-notify" class="btn btn-danger btn-sm">
                Atanan toplam iş sayısı: <span id="todo-count">
                    @(HomeController.GetTodoCount(HttpContext.Current.User.Identity.GetUserId()))
                </span>
            </button>
        }
    </footer>
    <!-- END: Footer-->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/app-assets/js/scripts/configs/horizontal-menu.js"></script>
    <script src="~/Scripts/jquery.signalR-2.4.1.js"></script>
    <script src="~/signalr/hubs"></script>
    <script src="~/Scripts/notifier.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>